### ISSUE TITLE
Kibana 3.1-Apache-Error-(36)File name too long

### ISSUE THREAD

**Issue by german23** [christian-marie/kibana3_auth#25]
Hi guys,

just upgraded to the new version of Kibana3_auth with the implemented Kibana3.1.

Everything is working fine but it looks like Kibana have changed the way they call for ES-aliases and since them if you select a wide timerange ( 14days+ ) you´ll get the following error in the apache log:

(36)File name too long: access to /logstash-2014.06.25,logstash-2014.06.26,logstash-2014.06.27,logstash-2014.06.28,logstash-2014.06.29,logstash-2014.06.30,logstash-2014.07.01,logstash-2014.07.02,logstash-2014.07.03,logstash-2014.07.04,logstash-2014.07.05,logstash-2014.07.06,logstash-2014.07.07,logstash-2014.07.08,logstash-2014.07.09,logstash-2014.07.10,logstash-2014.07.11,logstash-2014.07.12,logstash-2014.07.13,logstash-2014.07.14,logstash-2014.07.15,logstash-2014.07.16,logstash-2014.07.17,logstash-2014.07.18,logstash-2014.07.19,logstash-2014.07.20,logstash-2014.07.21,logstash-2014.07.22,logstash-2014.07.23,logstash-2014.07.24,logstash-2014.07.25/_aliases failed, referer: https://servername/

Well what i tried so far is to increase the http-request length of elasticsearch ( http.max_initial_line_length: 64kb ) and the one of Apache 
    (LimitRequestLine 1638000000000
        LimitRequestFieldSize 163800000000
        LimitXMLRequestBody 163800000000
        LimitRequestBody 0
        LimitRequestFields 5000000
)
but none of them worked.

Anyone got any help?

**Comment by christian-marie** [comment]
Sorry, I do, but motivation is another thing. Open source isn't free devops support, it's just code, if you can't get the code to work...

**Comment by christian-marie** [comment]
It's not much code
