### ISSUE TITLE
kibana3_auth Timeout

### ISSUE THREAD

**Issue by tpetrosy** [christian-marie/kibana3_auth#30]
Hi,
Kibana3_auth has request timeout 60 sec.
how is possible to increase the value ?

**Comment by tpetrosy** [comment]
seems the rb option
http.read_timeout = 500
solves problem in lib/forwarder.rb
will be grate to have timeout option in kibana3_auth configuration files.
Thanks!

**Comment by christian-marie** [comment]
I'll merge a PR that does just this :)

**Comment by german23** [comment]
I added a pull request with the necessary option for the http request

**Comment by christian-marie** [comment]
Thanks @german23
