### ISSUE TITLE
Configuration issue !

### ISSUE THREAD

**Issue by gugansankar** [christian-marie/kibana3_auth#34]
Hi,
I'm using Kibana for long time and now decided to implement kibana3_auth in my environment. As its seem Good one who decides/needs Authentication for Kibana

I'm new to this kibana3_auth. Readme file doesn't give enough info for newbie who willing to make use of this one. 

If possible, could you please share add more documentation on this. ? How we have to set it up .

Issue in my Lab setup:
1. How do I add the login user's IDs ?., and where users details will be stored.

**Comment by christian-marie** [comment]
I'm not working on this project anymore, sorry. Patches welcome.

**Comment by christian-marie** [comment]
To elaborate on this. I'm not here to provide *that* level of support. You write a ruby function in your configuration.rb that logs your user ids in. User details can be stored in memory, in a DB, ldap, whatever.

The "New installation" heading documents all off this, in the README.
